language: node_js
node_js:
  - "4.2.6"
install:
  - npm install mocha
  - npm install chai
script:
  - npm test
branches:
  only:
    - test

after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  ./merge.sh