language: node_js
node_js:
  - "4.2.6"
install:
  - npm install mocha
  - npm install chai
script:
  - npm test
branches:
  only:
<<<<<<< HEAD
    - test
=======
    - test

after_success:
  ./merge.sh